#include "Compiler/PackageManager/Lockfile.h"

#include "Common/BuildConfig/BuildConfig.h"
#include "Common/Checksum/Checksum.h"

#include <ctime>
#include <fstream>
#include <iomanip>
#include <ranges>
#include <sstream>
#include <toml.hpp>

namespace
{
	[[nodiscard]] std::string ToUtcTimestamp()
	{
		const std::time_t now = std::time(nullptr);
		std::tm utc_time{};
#ifdef _WIN32
		gmtime_s(&utc_time, &now);
#else
		gmtime_r(&now, &utc_time);
#endif

		std::ostringstream stream;
		stream << std::put_time(&utc_time, "%Y-%m-%dT%H:%M:%SZ");
		return stream.str();
	}

	[[nodiscard]] std::filesystem::path ResolveLockfileSource(std::string_view source, const std::filesystem::path& project_root)
	{
		if (source.starts_with("local:"))
		{
			return project_root / std::filesystem::path(std::string(source.substr(6u)));
		}
		return std::filesystem::path(source);
	}
}

namespace MidoriPackageManager
{
	std::expected<void, std::string> WriteLockfile(
		const ResolvedPackageGraph& graph,
		const std::filesystem::path& lockfile_path,
		std::string_view manifest_checksum)
	{
		toml::value document(toml::table{});
		document["metadata"] = toml::value(toml::table
		{
			{ "midori_version", std::string(MidoriBuild::VersionString) },
			{ "generated", ToUtcTimestamp() },
			{ "manifest_checksum", std::string(manifest_checksum) }
		});

		toml::array packages;
		for (const std::string& package_name : graph.TopologicalOrder())
		{
			const ResolvedPackage& package = graph.m_packages.at(package_name);
			std::string checksum = package.m_package_checksum;
			if (checksum.empty())
			{
				const std::expected<std::string, std::string> computed_checksum = MidoriChecksum::HashPackageSources(package.m_manifest.GetPackageDirectory());
				if (!computed_checksum.has_value())
				{
					return std::unexpected(computed_checksum.error());
				}
				checksum = computed_checksum.value();
			}

			toml::array dependencies;
			for (const std::string& dependency : package.m_dependencies)
			{
				const ResolvedPackage& dependency_package = graph.m_packages.at(dependency);
				dependencies.emplace_back(std::format(
					"{}@{}",
					dependency,
					dependency_package.m_manifest.GetInfo().m_version));
			}

			packages.emplace_back(toml::table
			{
				{ "name", package.m_manifest.GetInfo().m_name },
				{ "version", package.m_manifest.GetInfo().m_version },
				{ "source", package.m_source },
				{ "checksum", checksum },
				{ "dependencies", dependencies }
			});
		}

		document["package"] = toml::value(packages);

		std::ofstream output(lockfile_path, std::ios::binary | std::ios::trunc);
		if (!output.is_open())
		{
			return std::unexpected(std::format("Failed to open lockfile for writing: {}", lockfile_path.string()));
		}

		output << "# Auto-generated by Midori. Do not edit manually.\n";
		output << toml::format(document);
		if (!output.good())
		{
			return std::unexpected(std::format("Failed to write lockfile: {}", lockfile_path.string()));
		}

		return {};
	}

	std::expected<LockfileLoadResult, std::string> ReadLockfile(
		const std::filesystem::path& lockfile_path,
		std::string_view expected_manifest_checksum)
	{
		LockfileLoadResult result;
		if (!std::filesystem::exists(lockfile_path))
		{
			return std::unexpected(std::format("Lockfile not found: {}", lockfile_path.string()));
		}

		const toml::value document = toml::parse(lockfile_path);
		if (document.contains("metadata"))
		{
			const toml::value& metadata = document.at("metadata");
			const std::string manifest_checksum = toml::find_or<std::string>(metadata, "manifest_checksum", "");
			result.m_manifest_matches = manifest_checksum == expected_manifest_checksum;
		}

		if (!document.contains("package") || !document.at("package").is_array())
		{
			return result;
		}

		const std::filesystem::path project_root = lockfile_path.parent_path();
		for (const toml::value& package_value : document.at("package").as_array())
		{
			const std::string name = toml::find_or<std::string>(package_value, "name", "");
			const std::string version = toml::find_or<std::string>(package_value, "version", "");
			const std::string source = toml::find_or<std::string>(package_value, "source", "");
			const std::string checksum = toml::find_or<std::string>(package_value, "checksum", "");

			if (name.empty() || version.empty() || source.empty())
			{
				return std::unexpected(std::format("Malformed lockfile entry in {}", lockfile_path.string()));
			}

			const std::filesystem::path package_directory = ResolveLockfileSource(source, project_root);
			if (!std::filesystem::exists(package_directory))
			{
				result.m_packages_available = false;
				result.m_warnings.push_back(std::format("Locked package path is missing: {}", package_directory.string()));
				continue;
			}

			const std::expected<PackageManifest, std::string> manifest = PackageManifest::LoadWithError(package_directory);
			if (!manifest.has_value())
			{
				result.m_packages_available = false;
				result.m_warnings.push_back(manifest.error());
				continue;
			}

			if (manifest->GetInfo().m_name != name || manifest->GetInfo().m_version != version)
			{
				result.m_packages_available = false;
				result.m_warnings.push_back(std::format(
					"Locked package '{}' expected version {}, but found {} at {}.",
					name,
					version,
					manifest->GetInfo().m_version,
					package_directory.string()));
				continue;
			}

			if (!checksum.empty())
			{
				const std::expected<std::string, std::string> current_checksum = MidoriChecksum::HashPackageSources(package_directory);
				if (!current_checksum.has_value())
				{
					result.m_warnings.push_back(current_checksum.error());
				}
				else if (current_checksum.value() != checksum)
				{
					result.m_warnings.push_back(std::format(
						"Package '{}' has changed since the lockfile was generated.",
						name));
				}
			}

			ResolvedPackage resolved_package;
			resolved_package.m_manifest = manifest.value();
			resolved_package.m_source = source;
			resolved_package.m_package_checksum = checksum;

			if (package_value.contains("dependencies") && package_value.at("dependencies").is_array())
			{
				for (const toml::value& dependency_value : package_value.at("dependencies").as_array())
				{
					const std::string dependency_entry = dependency_value.as_string();
					const size_t separator = dependency_entry.find('@');
					resolved_package.m_dependencies.push_back(separator == std::string::npos ? dependency_entry : dependency_entry.substr(0u, separator));
				}
			}

			result.m_graph.m_packages[name] = std::move(resolved_package);
		}

		result.m_graph.m_root_dependencies.clear();
		for (const auto& [package_name, _] : result.m_graph.m_packages)
		{
			result.m_graph.m_root_dependencies.push_back(package_name);
		}
		std::ranges::sort(result.m_graph.m_root_dependencies);

		for (const auto& [_, resolved_package] : result.m_graph.m_packages)
		{
			for (const std::string& dependency : resolved_package.m_dependencies)
			{
				const auto it = std::ranges::find(result.m_graph.m_root_dependencies, dependency);
				if (it != result.m_graph.m_root_dependencies.end())
				{
					result.m_graph.m_root_dependencies.erase(it);
				}
			}
		}

		return result;
	}
}
